# Generated by Django 4.2.17 on 2025-01-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Image', 'Image')], max_length=10)),
            ],
        ),
    ]
